# This file contains the configuration for the training process + optional fine-tuning
batch_size: 96
training_epochs: 2
dataset_path: data
output_path: model/results/torch
img_height: 160
img_num_channels: 3
img_width: 160
model_name: torch_mbnv2
model_type: mobilenet # shufflenet, mobilenet, efficientnet, densenet, squeezenet
requires_grad: True
patience: 10
num_workers: 4
# The following parameters are used for fine-tuning
fine_tune: True
fine_tune_epochs: 10
fine_tuning_learning_rate: 0.00001
