# This file contains the configuration for the training process + optional fine-tuning
batch_size: 96
training_epochs: 50
dataset_path: data
output_path: results/torch
img_height: 32
img_num_channels: 3
img_width: 32
model_name: torch_squeezenet_cifar
model_type: squeezenet # shufflenet, mobilenet, efficientnet, densenet, squeezenet
requires_grad: True
patience: 10
num_workers: 4
# The following parameters are used for fine-tuning
fine_tune: True
fine_tune_epochs: 10
fine_tuning_learning_rate: 0.00001
