# Config for MobileNetV2 model compression calibrated on birdiary dataset
batch_size: 32
img_height: 224
img_width: 224
input_model_path: model/results/torch/torch_mbnv2/torch_mbnv2.pth
dataset_path: data/
output_path: model/results/torch/torch_mbnv2/
model_name: torch_mbnv2_layerwise_equalization
quant_config: LayerwiseEqualization_quantization # [None, "LayerwiseEqualization_quantization", "MixedPrecision_quantization"]